# Generated by Django 5.2.4 on 2025-08-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
