# Generated by Django 5.2.4 on 2025-11-17 15:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_message_delete_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gift_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_recipient',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
